const db = {
  "1h Blunt": {
    "Howling Skull": {
      name: "Howling Skull",
      min: 30,
      max: 50,
      type: "1h Blunt",
      blurb:
        "Drops from named mobs in TOTW. Replaced by Skull_of_Lamentation & Skull_of_Woe.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "1s", quality: "g" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "28", quality: "" },
        maxDamage: { value: "112", quality: "g" },
        critMod: { value: "6", quality: "" },
        attackCap: { value: "700", quality: "" },
        init: { value: "Melee", quality: "" },
        multi: { value: "112", quality: "g" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "1h Blunt": { value: "305", quality: "g" },
          "Fast attack": { value: "116", quality: "" },
        },
        mods: {},
      },
      profs: ["Enforcer", "Meta-Physicist"],
      auno: "https://auno.org/ao/db.php?id=204750",
      diff: 3,
    },
    "Skull of Woe": {
      name: "Skull of Woe",
      min: 50,
      max: 110,
      type: "1h Blunt",
      blurb:
        "Drops from Lien the Memorystalker in TOTW. Left hand only. Typical upgrade from Howling_Skull. Compliments Skull_of_Lamentation. Powerful, quick 1h blunt weapon that will last you until Mortiig_Beaters.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "1s", quality: "g" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "49", quality: "" },
        maxDamage: { value: "142", quality: "g" },
        critMod: { value: "11", quality: "" },
        attackCap: { value: "700", quality: "" },
        init: { value: "Melee", quality: "" },
        multi: { value: "112", quality: "g" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "1h Blunt": { value: "417", quality: "" },
          "Fast attack": { value: "201", quality: "" },
        },
        mods: { "Max health": { value: "15", quality: "" } },
      },
      profs: ["Enforcer", "Meta-Physicist"],
      prk: false,
      auno: "https://auno.org/ao/db.php?id=204751",
      diff: 4,
    },
    "Skull of Lamentation": {
      name: "Skull of Lamentation",
      min: 50,
      max: 110,
      type: "1h Blunt",
      blurb:
        "Drops from Lien the Memorystalker in TOTW. Right hand only. Typical upgrade from Howling_Skull. Compliments Skull_of_Woe. Powerful, quick 1h blunt weapon that will last you until Mortiig_Beaters.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "Yes", quality: "r" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "1s", quality: "g" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "52", quality: "" },
        maxDamage: { value: "140", quality: "g" },
        critMod: { value: "10", quality: "" },
        attackCap: { value: "700", quality: "" },
        init: { value: "Melee", quality: "" },
        multi: { value: "112", quality: "g" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "1h Blunt": { value: "417", quality: "" },
          "Fast attack": { value: "201", quality: "" },
        },
        mods: { "Max health": { value: "15", quality: "" } },
      },
      profs: ["Enforcer", "Meta-Physicist"],
      prk: false,
      auno: "https://auno.org/ao/db.php?id=204752",
      diff: 4,
    },
    "Mortiig Beater of Torture": {
      name: "Mortiig Beater of Torture",
      min: 100,
      max: 200,
      type: "1h Blunt",
      blurb:
        "Drops from Mortiig bosses in Elysium, Shadowlands. Enforcer only. Notable locations include Spade Beach and Eastfang. Model list is QL 125 interpolation. Every 5 levels it gets a different adjective in its name. High damage profile and low reqs make it an attractive weapon for mid-late game. Limited end game use due to low MBS.",
      stats: {
        ql: { value: "100-125", quality: "r" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "1s", quality: "g" },
        range: { value: "2 m", quality: "" },
        minDamage: { value: "75", quality: "" },
        maxDamage: { value: "450", quality: "g" },
        critMod: { value: "75", quality: "" },
        attackCap: { value: "750", quality: "r" },
        init: { value: "Melee", quality: "" },
        multi: { value: "625", quality: "" },
        specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
        reqs: {
          "Expansion sets": { value: "Shadowlands", quality: "r" },
          Profession: { value: "Enforcer", quality: "r" },
          "1h Blunt": { value: "626", quality: "g" },
          "Fast attack": { value: "313", quality: "" },
          Brawl: { value: "376", quality: "" },
          Dimach: { value: "126", quality: "" },
        },
        mods: { "Body development": { value: "40", quality: "" } },
      },
      profs: ["Enforcer"],
      prk: false,
      diff: 4,
      auno: "https://auno.org/ao/db.php?id=246355",
    },
    "Skull of Misery": {
      name: "Skull of Misery",
      min: 175,
      max: 220,
      type: "1h Blunt",
      blurb:
        "Drops in third floor IS. Left hand only. One of the best in class, on RK. Low MBS limits end game potential. Compliments Skull_of_Despair.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "Yes", quality: "r" },
        aSpeed: { value: "2.2s", quality: "" },
        rSpeed: { value: "1.2s", quality: "g" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "120", quality: "" },
        maxDamage: { value: "506", quality: "g" },
        critMod: { value: "104", quality: "" },
        attackCap: { value: "1200", quality: "r" },
        init: { value: "Melee", quality: "" },
        multi: { value: "904", quality: "r" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "1h Blunt": { value: "1049", quality: "r" },
          "Fast attack": { value: "809", quality: "" },
        },
        mods: { "Max health": { value: "25", quality: "" } },
      },
      profs: ["Enforcer", "Meta-Physicist"],
      auno: "https://auno.org/ao/db.php?id=206059",
      diff: 6,
    },
    "Skull of Despair": {
      name: "Skull of Despair",
      min: 175,
      max: 220,
      type: "1h Blunt",
      blurb:
        "Drops in third floor IS. Right hand only. One of the best in class, on RK. Low MBS limits end game potential. Compliments Skull_of_Misery.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "Yes", quality: "r" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "3s", quality: "r" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "170", quality: "" },
        maxDamage: { value: "558", quality: "g" },
        critMod: { value: "33", quality: "" },
        attackCap: { value: "1200", quality: "r" },
        init: { value: "Melee", quality: "" },
        multi: { value: "904", quality: "r" },
        specials: { value: "", quality: "" },
        reqs: { "1h Blunt": { value: "1049", quality: "r" } },
        mods: { "Max health": { value: "25", quality: "" } },
      },
      profs: ["Enforcer", "Meta-Physicist"],
      prk: false,
      diff: 6,
      auno: "https://auno.org/ao/db.php?id=206060",
    },
  },

  "1h Edged": {
    "Super SOL Fire Executioner Type F": {
      name: "Super SOL Fire Executioner Type F",
      min: 1,
      max: 200,
      type: "1h Edged",
      blurb:
        "Most notably drops from random mobs in the Subway. Also drops from Dynas. Model listed is QL 200 interpolation. Comes in 4 different flavors C, E, T, F. Each variant has a different specials, with type F having all of them minus sneak attack. Common upgrade from starting swords. QLs 1-199 are named SOL Fire Executioner Type F.",
      stats: {
        ql: { value: "1-200", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "2s", quality: "" },
        rSpeed: { value: "2s", quality: "" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "50", quality: "" },
        maxDamage: { value: "350", quality: "" },
        critMod: { value: "250", quality: "" },
        attackCap: { value: "2500", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "830", quality: "" },
        specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
        reqs: {
          Profession: { value: "Adventurer", quality: "r" },
          "1h Edged": { value: "1036", quality: "" },
          "Fast attack": { value: "519", quality: "" },
          Brawl: { value: "622", quality: "" },
          Dimach: { value: "208", quality: "" },
        },
        mods: { "Evade close": { value: "20", quality: "" } },
      },
      profs: ["Adventurer"],
      prk: false,
      diff: 2,
      auno: "https://auno.org/ao/db.php?id=160238",
    },
    "Phase Blade": {
      name: "Phase Blade",
      min: 30,
      max: 50,
      type: "1h Edged",
      blurb:
        "Drops from named mobs in TOTW. Naturally upgrades to Frozen_Tear_of_Uklesh.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "2s", quality: "" },
        rSpeed: { value: "2s", quality: "" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "35", quality: "" },
        maxDamage: { value: "121", quality: "g" },
        critMod: { value: "0", quality: "" },
        attackCap: { value: "700", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "165", quality: "g" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "1h Edged": { value: "305", quality: "" },
          "Fast attack": { value: "146", quality: "" },
        },
        mods: {},
      },
      profs: ["Enforcer", "Adventurer"],
      prk: false,
      diff: 3,
      auno: "https://auno.org/ao/db.php?id=204745",
    },
    "Frozen Tear of Uklesh": {
      name: "Frozen Tear of Uklesh",
      min: 50,
      max: 100,
      type: "1h Edged",
      blurb:
        "Drops from Uklesh the Frozen, Aztur the Immortal's placeholder in TOTW. Hits have a 8% chance to proc an extra 400 damage.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "2s", quality: "" },
        rSpeed: { value: "2s", quality: "" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "95", quality: "" },
        maxDamage: { value: "148", quality: "g" },
        critMod: { value: "0", quality: "" },
        attackCap: { value: "700", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "230", quality: "" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "1h Edged": { value: "357", quality: "g" },
          "Fast attack": { value: "181", quality: "" },
        },
        mods: {},
      },
      profs: ["Enforcer", "Adventurer"],
      prk: false,
      diff: 5,
      auno: "https://auno.org/ao/db.php?id=204739",
    },
    "Crispy Chiroptera": {
      name: "Crispy Chiroptera",
      min: 80,
      max: 200,
      type: "1h Edged",
      blurb:
        "Drops from Cenobite Shadows in COH. Profession locked to Enforcer and Adventurer. Model listed is QL 105 interpolation. Stats vary significantly across the 5 QLs.",
      stats: {
        ql: { value: "100-105", quality: "r" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "1.25s", quality: "g" },
        rSpeed: { value: "1.25s", quality: "g" },
        range: { value: "2 m", quality: "" },
        minDamage: { value: "100", quality: "" },
        maxDamage: { value: "550", quality: "g" },
        critMod: { value: "100", quality: "" },
        attackCap: { value: "1250", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "1000", quality: "r" },
        specials: {
          value: "Fast Attack, Sneak Attack, Brawl, Dimach",
          quality: "g",
        },
        reqs: {
          Profession: { value: "Enforcer or Adventurer", quality: "r" },
          "1h Edged": { value: "1001", quality: "" },
          "Sneak attack": { value: "501", quality: "" },
          "Fast attack": { value: "501", quality: "" },
          Brawl: { value: "601", quality: "" },
          Dimach: { value: "201", quality: "" },
        },
        mods: {
          "Nano pool": { value: "40", quality: "" },
          "Nano cost modifier": { value: "2", quality: "" },
        },
      },
      profs: ["Enforcer", "Adventurer"],
      prk: false,
      diff: 4,
      auno: "https://auno.org/ao/db.php?id=246714",
    },
  },
  "2h Blunt": {
    "Support Beam of Intolerance": {
      name: "Support Beam of Intolerance",
      min: 10,
      max: 40,
      type: "2h Blunt",
      blurb:
        "Drops from Workman Striker mobs in the Subway. One high level Workman Striker mob can be found in deep Subway to drop the higher QLs. Model listed is QL 30 interpolation. QL is hidden in game. Breed locked to Atrox. High damage makes up for slow attacks.",
      stats: {
        ql: { value: "10-30", quality: "r" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "3.5s", quality: "r" },
        rSpeed: { value: "2.5s", quality: "" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "11", quality: "" },
        maxDamage: { value: "122", quality: "g" },
        critMod: { value: "114", quality: "" },
        attackCap: { value: "", quality: "" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Brawl, Dimach", quality: "" },
        reqs: {
          Breed: { value: "Atrox", quality: "r" },
          "2h Blunt": { value: "202", quality: "" },
          Brawl: { value: "123", quality: "" },
          Dimach: { value: "44", quality: "" },
          Psychology: { value: "101", quality: "r" },
        },
        mods: { "Max health": { value: "20", quality: "" } },
      },
      profs: ["Enforcer", "Meta-Physicist"],
      prk: false,
      diff: 1,
      auno: "https://auno.org/ao/db.php?id=202720",
    },
    "Cold Morning Icebreaker": {
      name: "Cold Morning Icebreaker",
      min: 25,
      max: 60,
      type: "2h Blunt",
      blurb:
        'Drops from Dynas. Model listed is QL 50 interpolation. Named "Icebreaker" in lower QLs. Enforcer only. Notorious level 1 twink weapon due to low reqs, high damage and specials.',
      stats: {
        ql: { value: "40-50", quality: "r" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "2.2s", quality: "" },
        rSpeed: { value: "2.2s", quality: "" },
        range: { value: "4 m", quality: "" },
        minDamage: { value: "75", quality: "" },
        maxDamage: { value: "175", quality: "g" },
        critMod: { value: "175", quality: "" },
        attackCap: { value: "2500", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
        reqs: {
          Profession: { value: "Enforcer", quality: "r" },
          "2h Blunt": { value: "248", quality: "g" },
          "Fast attack": { value: "125", quality: "" },
          Brawl: { value: "149", quality: "" },
          Dimach: { value: "50", quality: "" },
        },
        mods: {
          "Max health": { value: "40", quality: "" },
          "Melee AC": { value: "60", quality: "" },
          "Melee init": { value: "20", quality: "" },
        },
      },
      profs: ["Enforcer"],
      prk: false,
      diff: 3,
      auno: "https://auno.org/ao/db.php?id=208061",
    },
    "Neleb's Nightmare Battlerod": {
      versions: [
        {
          name: "Neleb's Nightmare Battlerod",
          min: 40,
          max: 125,
          type: "2h Blunt",
          blurb:
            "Neleb the Deranged's rod. The weapon base drops from Neleb, and is then upgraded with items you find in Steps_of_Madness. The best early game 2h Blunt weapon due to high damage and low equip checks. Hits transfer 5 nano from the target to the user.",
          stats: {
            ql: { value: "53", quality: "" },
            dual: { value: "No", quality: "" },
            aSpeed: { value: "1.5s", quality: "g" },
            rSpeed: { value: "3s", quality: "r" },
            range: { value: "4 m", quality: "" },
            minDamage: { value: "75", quality: "" },
            maxDamage: { value: "330", quality: "g" },
            critMod: { value: "30", quality: "" },
            attackCap: { value: "800", quality: "g" },
            init: { value: "Melee", quality: "" },
            multi: { value: "", quality: "" },
            specials: { value: "Fast Attack", quality: "" },
            reqs: {
              "2h Blunt": { value: "351", quality: "g" },
              "Fast attack": { value: "201", quality: "" },
            },
            mods: { "Max nano": { value: "100", quality: "" } },
          },
          profs: ["Enforcer", "Meta-Physicist", "Doctor"],
          prk: false,
          auno: "https://auno.org/ao/db.php?id=274955&patch=18085300",
          diff: 5,
        },
        {
          name: "Neleb's Nightmare Battlerod",
          min: 40,
          max: 125,
          type: "2h Blunt",
          blurb:
            "Neleb the Deranged's rod. The weapon base drops from Neleb, and is then upgraded with items you find in Steps_of_Madness. The best early game 2h Blunt weapon due to high damage and low equip checks. Hits transfer 20 nano from the target to the user, making it a popular choice among enforcers and doctors to cast heals in prolonged engagements.",
          stats: {
            ql: { value: "53", quality: "" },
            dual: { value: "No", quality: "" },
            aSpeed: { value: "1s", quality: "g" },
            rSpeed: { value: "3s", quality: "r" },
            range: { value: "4 m", quality: "" },
            minDamage: { value: "75", quality: "" },
            maxDamage: { value: "330", quality: "g" },
            critMod: { value: "30", quality: "" },
            attackCap: { value: "800", quality: "g" },
            init: { value: "Melee", quality: "" },
            multi: { value: "", quality: "" },
            specials: { value: "Fast Attack", quality: "" },
            reqs: {
              "2h Blunt": { value: "351", quality: "g" },
              "Fast attack": { value: "201", quality: "" },
            },
            mods: { "Max nano": { value: "100", quality: "" } },
          },
          profs: ["Enforcer", "Meta-Physicist", "Doctor"],
          prk: true,
          auno: "https://auno.org/ao/db.php?id=274955&patch=17090000",
          diff: 5,
        },
      ],
    },
    "Hungry Howlet": {
      name: "Hungry Howlet",
      min: 80,
      max: 200,
      type: "2h Blunt",
      blurb:
        "Drops from Cenobite Shadows in COH. Profession locked to Enforcer and Meta-Physicist. Model listed is QL 105 interpolation. Stats vary significantly across the 5 QLs.",
      stats: {
        ql: { value: "100-105", quality: "r" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "1.25s", quality: "g" },
        rSpeed: { value: "1.25s", quality: "g" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "125", quality: "" },
        maxDamage: { value: "625", quality: "g" },
        critMod: { value: "125", quality: "" },
        attackCap: { value: "1250", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
        reqs: {
          Profession: { value: "Meta-Physicist or Enforcer", quality: "r" },
          "2h Blunt": { value: "1001", quality: "" },
          "Fast attack": { value: "501", quality: "" },
          Brawl: { value: "601", quality: "" },
          Dimach: { value: "201", quality: "" },
        },
        mods: {
          "Nano pool": { value: "40", quality: "" },
          "Nano cost modifier": { value: "2", quality: "" },
        },
      },
      profs: ["Enforcer", "Meta-Physicist"],
      prk: false,
      diff: 0,
      auno: "https://auno.org/ao/db.php?id=246709",
    },
    "Punishment Rod": {
      name: "Punishment Rod",
      min: 185,
      max: 220,
      type: "2h Blunt",
      blurb:
        "Drops from Obediency_Enforcer. Enforcer only and level locked to 185. Slow attack speed but high max damage makes it an effective RK end-game weapon. Low MBS limits it compared to expansion alternatives.",
      stats: {
        ql: { value: "200", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "5.2s", quality: "r" },
        rSpeed: { value: "4s", quality: "r" },
        range: { value: "4 m", quality: "" },
        minDamage: { value: "427", quality: "" },
        maxDamage: { value: "1127", quality: "g" },
        critMod: { value: "6", quality: "" },
        attackCap: { value: "1200", quality: "r" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          Profession: { value: "Enforcer", quality: "r" },
          "2h Blunt": { value: "1010", quality: "" },
          "Fast attack": { value: "620", quality: "" },
          Level: { value: "185", quality: "r" },
        },
        mods: {},
      },
      profs: ["Enforcer"],
      prk: false,
      diff: 6,
      auno: "https://auno.org/ao/db.php?id=201943",
    },
  },
  "2h Edged": {
    "Guard of the Gentleman": {
      name: "Guard of the Gentleman",
      min: 1,
      max: 50,
      type: "2h Edged",
      blurb:
        "Sold by Shadowlands melee weapons vendors in the sided gardens. Part of some common SL loot pools. A powerful enf and keeper sword that gets worse as it levels. Model listed is QL 29 interpolation. Upgrades to Energy_Scythe.",
      stats: {
        ql: { value: "1-300", quality: "r" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "1.19s", quality: "g" },
        rSpeed: { value: "1.19s", quality: "g" },
        range: { value: "2 m", quality: "" },
        minDamage: { value: "5", quality: "" },
        maxDamage: { value: "84", quality: "g" },
        critMod: { value: "37", quality: "" },
        attackCap: { value: "214", quality: "r" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fast Attack, Dimach", quality: "r" },
        reqs: {
          Profession: { value: "Enforcer or Keeper", quality: "r" },
          "2h Edged": { value: "175", quality: "g" },
          "Fast attack": { value: "88", quality: "" },
          Dimach: { value: "36", quality: "" },
        },
        mods: {},
      },
      profs: ["Enforcer", "Keeper"],
      prk: false,
      diff: 0,
      auno: "https://auno.org/ao/db.php?id=231255",
    },
    "Energy Scythe": {
      name: "Energy Scythe",
      min: 30,
      max: 50,
      type: "2h Edged",
      blurb:
        "Drops from named mobs in TOTW. Slow attacks but high damage. Upgrades naturally to Frost_Scythe_of_the_Legionnaire.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "2.8s", quality: "" },
        rSpeed: { value: "3.2s", quality: "r" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "92", quality: "" },
        maxDamage: { value: "224", quality: "g" },
        critMod: { value: "37", quality: "" },
        attackCap: { value: "700", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "2h Edged": { value: "305", quality: "g" },
          "Fast attack": { value: "161", quality: "" },
        },
        mods: {},
      },
      profs: ["Enforcer", "Keeper"],
      prk: false,
      diff: 3,
      auno: "https://auno.org/ao/db.php?id=204747",
    },
    "Frost Scythe of the Legionnaire": {
      name: "Frost Scythe of the Legionnaire",
      min: 40,
      max: 80,
      type: "2h Edged",
      blurb:
        "Drops from Deathless Legionnaires in TOTW. Flat damage makes it an effective weapon against armored SL mobs. Upgrades naturally to Stygian_Desolator.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "2.8s", quality: "" },
        rSpeed: { value: "3.2s", quality: "r" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "227", quality: "g" },
        maxDamage: { value: "227", quality: "g" },
        critMod: { value: "0", quality: "" },
        attackCap: { value: "700", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "2h Edged": { value: "357", quality: "g" },
          "Fast attack": { value: "191", quality: "" },
        },
        mods: { "Max health": { value: "15", quality: "" } },
      },
      profs: ["Enforcer", "Keeper"],
      prk: false,
      diff: 3,
      auno: "https://auno.org/ao/db.php?id=204746",
    },

    "Stygian Desolator": {
      name: "Stygian Desolator",
      min: 50,
      max: 130,
      type: "2h Edged",
      blurb:
        "Aztur the Immortal's sword. Drops in TOTW. Hits have a 6% to activate its proc, which applies a DOT and AAD/AAO debuff. Exceptional damage profile with a high MBS gives it a lot of potential. Arguably the best weapon in class and often a fallback choice for professions with poor weapon paths.",
      stats: {
        ql: { value: "SPECIAL", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "3.3s", quality: "r" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "75", quality: "" },
        maxDamage: { value: "331", quality: "g" },
        critMod: { value: "33", quality: "" },
        attackCap: { value: "800", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fast Attack", quality: "" },
        reqs: {
          "2h Edged": { value: "434", quality: "g" },
          "Fast attack": { value: "245", quality: "" },
        },
        mods: {
          "Max health": { value: "20", quality: "" },
          "Energy AC": { value: "80", quality: "" },
        },
      },
      profs: ["Enforcer", "Keeper"],
      auno: "https://auno.org/ao/db.php?id=204755",
      diff: 5,
    },
    "Pained Panther": {
      versions: [
        {
          name: "Pained Panther",
          min: 80,
          max: 200,
          type: "2h Edged",
          blurb:
            "Drops from Cenobite Shadows in COH. Profession locked to Keeper, Enforcer and Meta-Physicist. Model listed is QL 105 interpolation. Stats vary significantly across the 5 QLs.",
          stats: {
            ql: { value: "100-105", quality: "r" },
            dual: { value: "No", quality: "" },
            aSpeed: { value: "1.25s", quality: "g" },
            rSpeed: { value: "1.25s", quality: "g" },
            range: { value: "3 m", quality: "" },
            minDamage: { value: "125", quality: "" },
            maxDamage: { value: "625", quality: "g" },
            critMod: { value: "125", quality: "" },
            attackCap: { value: "1250", quality: "r" },
            init: { value: "Melee", quality: "" },
            multi: { value: "", quality: "" },
            specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
            reqs: {
              Profession: {
                value: "Keeper, Enforcer or Meta-Physicist",
                quality: "r",
              },
              "2h Edged": { value: "1000", quality: "r" },
              "Fast attack": { value: "500", quality: "" },
              Brawl: { value: "600", quality: "" },
              Dimach: { value: "200", quality: "" },
            },
            mods: {
              "Nano pool": { value: "40", quality: "" },
              "Nano cost modifier": { value: "2", quality: "" },
            },
          },
          profs: ["Keeper", "Enforcer", "Meta-Physicist"],
          prk: false,
          diff: 4,
          auno: "https://auno.org/ao/db.php?id=246719",
        },
        {
          name: "Pained Panther",
          min: 100,
          max: 200,
          type: "2h Edged",
          blurb:
            "Drops from Cenobite Shadows in COH. Profession locked to Enforcer and Meta-Physicist. Model listed is QL 105 interpolation. Stats vary significantly across the 5 QLs.",
          stats: {
            ql: { value: "100-105", quality: "r" },
            dual: { value: "No", quality: "" },
            aSpeed: { value: "1.25s", quality: "g" },
            rSpeed: { value: "1.25s", quality: "g" },
            range: { value: "3 m", quality: "" },
            minDamage: { value: "125", quality: "" },
            maxDamage: { value: "625", quality: "g" },
            critMod: { value: "125", quality: "" },
            attackCap: { value: "1250", quality: "r" },
            init: { value: "Melee", quality: "" },
            multi: { value: "", quality: "" },
            specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
            reqs: {
              Profession: { value: "Enforcer or Meta-Physicist", quality: "r" },
              "2h Edged": { value: "1001", quality: "r" },
              "Fast attack": { value: "501", quality: "" },
              Brawl: { value: "601", quality: "" },
              Dimach: { value: "201", quality: "" },
            },
            mods: {
              "Nano pool": { value: "40", quality: "" },
              "Nano cost modifier": { value: "2", quality: "" },
            },
          },
          profs: ["Enforcer", "Meta-Physicist"],
          prk: true,
          diff: 4,
          auno: "https://auno.org/ao/db.php?id=246719&patch=15050000",
        },
      ],
    },
  },

  "Martial arts": {
    "Lotus Parry Stick": {
      name: "Lotus Parry Stick",
      min: 1,
      max: 125,
      type: "Martial arts",
      blurb:
        "Blitzable and part of common loot pools. Model listed is QL 200 interpolation. Hard for MAs to use because of the 1hb and multi check, but sees some use on traders due to high damage from MA drain transfers.",
      stats: {
        ql: { value: "1-200", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "2.5s", quality: "" },
        rSpeed: { value: "3.5s", quality: "r" },
        range: { value: "3 m", quality: "" },
        minDamage: { value: "50", quality: "" },
        maxDamage: { value: "350", quality: "" },
        critMod: { value: "350", quality: "" },
        attackCap: { value: "2300", quality: "g" },
        init: { value: "Physical", quality: "r" },
        multi: { value: "777", quality: "r" },
        specials: { value: "Brawl, Dimach", quality: "" },
        reqs: {
          "Martial arts": { value: "806", quality: "" },
          "1h Blunt": { value: "537", quality: "" },
          Brawl: { value: "537", quality: "" },
          Dimach: { value: "180", quality: "" },
        },
        mods: {
          Parry: { value: "100", quality: "" },
          "Evade close": { value: "100", quality: "" },
        },
      },
      auno: "https://auno.org/ao/db.php?id=152357",
      profs: ["Martial Artist", "Trader"],
      diff: 2,
    },
    "Nano-Charged Stun Glove - 870": {
      versions: [
        {
          name: "Nano-Charged Stun Glove - 870",
          min: 1,
          max: 200,
          type: "Martial arts",
          blurb:
            "Sold in stores and craftable_with_weapon_upgrade_kits. Model listed is QL 300 variant of the highest upgrade tier. Popular among traders for the additional attack bar to proc perks.",
          stats: {
            ql: { value: "1-300", quality: "" },
            dual: { value: "Yes", quality: "" },
            aSpeed: { value: "1.5s", quality: "g" },
            rSpeed: { value: "1.5s", quality: "g" },
            range: { value: "3 m", quality: "" },
            minDamage: { value: "140", quality: "" },
            maxDamage: { value: "440", quality: "g" },
            critMod: { value: "240", quality: "" },
            attackCap: { value: "2400", quality: "g" },
            init: { value: "Physical", quality: "r" },
            multi: { value: "1200", quality: "r" },
            specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
            reqs: {
              "Martial arts": { value: "1501", quality: "r" },
              Brawl: { value: "901", quality: "" },
              "Fast attack": { value: "751", quality: "" },
              Dimach: { value: "301", quality: "" },
            },
            mods: {},
          },
          profs: ["Trader", "Martial Artist"],
          prk: false,
          auno: "https://auno.org/ao/db.php?id=271047&ql=200",
          diff: 1,
        },
        {
          name: "Nano-Charged Stun Glove - 870",
          min: 1,
          max: 200,
          type: "1h Blunt",
          blurb:
            "Last known to be buyable from Weapon Fragment stores in ICC and craftable_with_weapon_upgrade_kits. Model listed is QL 300 variant of the highest upgrade tier. Popular among traders for the additional attack bar to proc perks. Uses 1h Blunt skill instead of Martial Arts.",
          stats: {
            ql: { value: "1-300", quality: "" },
            dual: { value: "Yes", quality: "" },
            aSpeed: { value: "1.5s", quality: "g" },
            rSpeed: { value: "1.5s", quality: "g" },
            range: { value: "3 m", quality: "" },
            minDamage: { value: "240", quality: "" },
            maxDamage: { value: "340", quality: "" },
            critMod: { value: "240", quality: "" },
            attackCap: { value: "2400", quality: "g" },
            init: { value: "Melee", quality: "r" },
            multi: { value: "1200", quality: "r" },
            specials: { value: "Fast Attack, Brawl, Dimach", quality: "g" },
            reqs: {
              "1h Blunt": { value: "2001", quality: "r" },
              Brawl: { value: "1201", quality: "" },
              "Fast attack": { value: "1001", quality: "" },
              Dimach: { value: "401", quality: "" },
            },
            mods: {},
          },
          profs: ["Enforcer", "Meta-Physicist", "Trader"],
          prk: true,
          auno: "https://auno.org/ao/db.php?id=271047&patch=17060000",
          diff: 0,
        },
      ],
    },
  },
  "Melee energy": {
    "Gift of Jupiter": {
      name: "Gift of Jupiter",
      min: 25,
      max: 60,
      type: "Melee energy",
      blurb:
        "Drops from Dynas. Meta-Physicist only. QL makes it hard to drop when you can first equip. AAD mods, low reqs and damage make it an attractive alternative to creation shields.",
      stats: {
        ql: { value: "50", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "2.5s", quality: "" },
        rSpeed: { value: "2.5s", quality: "" },
        range: { value: "2 m", quality: "" },
        minDamage: { value: "25", quality: "" },
        maxDamage: { value: "200", quality: "g" },
        critMod: { value: "100", quality: "" },
        attackCap: { value: "2500", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "211", quality: "g" },
        specials: { value: "Fast Attack, Brawl", quality: "g" },
        reqs: {
          Profession: { value: "Meta-Physicist", quality: "r" },
          "Melee energy": { value: "213", quality: "g" },
          "Fast attack": { value: "107", quality: "" },
          Brawl: { value: "128", quality: "" },
        },
        mods: {
          "Radiation AC": { value: "80", quality: "" },
          "Nano init": { value: "20", quality: "" },
          "Defense modifier": { value: "20", quality: "" },
        },
      },
      profs: ["Meta-Physicist"],
      prk: false,
      diff: 4,
      auno: "https://auno.org/ao/db.php?id=208071",
    },
  },
  Piercing: {
    "Fear-forged Blade": {
      name: "Fear-forged Blade",
      min: 40,
      max: 80,
      type: "Piercing",
      blurb:
        "Drops from Unrelenting Fear in Steps_of_Madness. The best early game piercing weapon. Hits have a 5% chance to proc a DOT.",
      stats: {
        ql: { value: "50", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "1.08s", quality: "g" },
        rSpeed: { value: "1.3s", quality: "g" },
        range: { value: "1 m", quality: "r" },
        minDamage: { value: "45", quality: "" },
        maxDamage: { value: "125", quality: "g" },
        critMod: { value: "50", quality: "" },
        attackCap: { value: "720", quality: "g" },
        init: { value: "Melee", quality: "" },
        multi: { value: "122", quality: "g" },
        specials: { value: "Fast Attack, Sneak Attack", quality: "" },
        reqs: {
          Piercing: { value: "301", quality: "g" },
          "Sneak attack": { value: "151", quality: "" },
          "Fast attack": { value: "101", quality: "" },
        },
        mods: { Piercing: { value: "20", quality: "" } },
      },
      auno: "https://auno.org/ao/db.php?id=151903",
      profs: ["Shade"],
      diff: 4,
    },
  },
  "Assault rifle": {
    "Neutrino Flash": {
      name: "Neutrino Flash",
      min: 40,
      max: 100,
      type: "Assault rifle",
      blurb:
        "Drops from Notum Habit in Steps_of_Madness. The best early game assault rifle with good damage and fast attacks. Hits have a 5% chance to proc a reflect shutdown.",
      stats: {
        ql: { value: "50", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "1s", quality: "g" },
        range: { value: "21 m", quality: "" },
        minDamage: { value: "50", quality: "" },
        maxDamage: { value: "160", quality: "g" },
        critMod: { value: "75", quality: "" },
        attackCap: { value: "730", quality: "g" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Burst", quality: "" },
        reqs: {
          "Assault rifle": { value: "301", quality: "g" },
          Burst: { value: "151", quality: "" },
        },
        mods: {},
      },
      auno: "https://auno.org/ao/db.php?id=152027",
      profs: ["Soldier"],
      diff: 4,
    },
  },
  Bow: {
    "Howling Bow of Ferocious Appetite": {
      name: "Howling Bow of Ferocious Appetite",
      min: 1,
      max: 200,
      type: "Bow",
      blurb:
        "Part of common loot pools. Model listed is QL 200 interpolation. Decent damage profile makes it one of the few viable bows. Crits stack well with Martial Artists.",
      stats: {
        ql: { value: "1-200", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "2.8s", quality: "" },
        rSpeed: { value: "2.2s", quality: "" },
        range: { value: "28 m", quality: "" },
        minDamage: { value: "85", quality: "" },
        maxDamage: { value: "450", quality: "g" },
        critMod: { value: "600", quality: "g" },
        attackCap: { value: "2400", quality: "g" },
        init: { value: "Physical", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "", quality: "r" },
        reqs: { Bow: { value: "1001", quality: "" } },
        mods: {
          "Max health": { value: "160", quality: "" },
          Stamina: { value: "8", quality: "" },
          "Bow special attack": { value: "12", quality: "" },
        },
      },
      profs: ["Martial Artist"],
      prk: false,
      diff: 2,
      auno: "https://auno.org/ao/db.php?id=165059&ql=200",
    },
  },
  Grenade: {
    "Red Line Grenade Launcher": {
      name: "Red Line Grenade Launcher",
      min: 25,
      max: 60,
      type: "Grenade",
      blurb:
        "Drops from Dynas. Engineer only. Right hand only. Slow hits and big damage.",
      stats: {
        ql: { value: "40-50", quality: "" },
        dual: { value: "Yes", quality: "r" },
        aSpeed: { value: "3s", quality: "r" },
        rSpeed: { value: "3s", quality: "r" },
        range: { value: "30 m", quality: "" },
        minDamage: { value: "5", quality: "" },
        maxDamage: { value: "400", quality: "g" },
        critMod: { value: "20", quality: "" },
        attackCap: { value: "2500", quality: "g" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "217", quality: "" },
        specials: { value: "", quality: "" },
        reqs: {
          Profession: { value: "Engineer", quality: "r" },
          Grenade: { value: "218", quality: "g" },
        },
        mods: {
          "Chemical AC": { value: "60", quality: "" },
          "Fire AC": { value: "60", quality: "" },
          "Mechanical engineering": { value: "30", quality: "" },
        },
      },
      profs: ["Engineer"],
      prk: false,
      diff: 4,
      auno: "https://auno.org/ao/db.php?id=208039",
    },
  },
  Pistol: {
    "Solar Powered Tinker Pistol": {
      name: "Solar Powered Tinker Pistol",
      min: 1,
      max: 220,
      type: "Pistol",
      blurb:
        'Pistol built_from_the_starting_solar_powered_pistol. Right hand only. Model listed is QL 1 interpolation. One of the few "leveling weapons" in the game. Has to be upgraded with items roughly every 40 levels. End game variants are powerful but weapon smithing checks can make it hard to use off-class.',
      stats: {
        ql: { value: "Interpolated", quality: "r" },
        dual: { value: "Yes", quality: "r" },
        aSpeed: { value: "1.7s", quality: "" },
        rSpeed: { value: "1.2s", quality: "g" },
        range: { value: "15 m", quality: "" },
        minDamage: { value: "3", quality: "" },
        maxDamage: { value: "16", quality: "g" },
        critMod: { value: "20", quality: "g" },
        attackCap: { value: "", quality: "" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "", quality: "" },
        reqs: {
          Pistol: { value: "9", quality: "" },
          "Weapon smithing": { value: "6", quality: "r" },
        },
        mods: {
          "Max Health": { value: "1", quality: "" },
          "Max Nano": { value: "1", quality: "" },
          Tutoring: { value: "1", quality: "" },
        },
      },
      auno: "https://auno.org/ao/db.php?id=164489",
      profs: ["Engineer", "Adventurer", "Nano-technician"],
      diff: 69,
    },
    "Dark Pistol of The Revoked": {
      name: "Dark Pistol of The Revoked",
      min: 80,
      max: 175,
      type: "Pistol",
      blurb:
        'Drops from Dark Cenobites & Summoners in COH. The mobs can be accessed in the entrance before you need a team to go deeper. Left hand and Bureaucrat only. Model listed is QL 100 interpolation. Named "Dark Pistol" in the 75-94 range.',
      stats: {
        ql: { value: "75-94 + 100", quality: "r" },
        dual: { value: "Yes", quality: "r" },
        aSpeed: { value: "1.2s", quality: "g" },
        rSpeed: { value: "1.2s", quality: "g" },
        range: { value: "22 m", quality: "" },
        minDamage: { value: "75", quality: "" },
        maxDamage: { value: "190", quality: "g" },
        critMod: { value: "150", quality: "" },
        attackCap: { value: "1000", quality: "g" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "500", quality: "" },
        specials: { value: "Fling Shot", quality: "" },
        reqs: {
          Profession: { value: "Bureaucrat", quality: "r" },
          Pistol: { value: "521", quality: "" },
          "Fling shot": { value: "261", quality: "" },
        },
        mods: {
          Intelligence: { value: "25", quality: "" },
          "Max nano": { value: "150", quality: "" },
          "Experience modifier": { value: "3", quality: "" },
        },
      },
      profs: ["Bureaucrat"],
      prk: false,
      auno: "https://auno.org/ao/db.php?id=245223",
      diff: 3,
    },
  },
  Rifle: {
    "Assassins FDA Caterwaul 913": {
      name: "Assassins FDA Caterwaul 913",
      min: 1,
      max: 200,
      type: "Rifle",
      blurb:
        "Blitzable and part of common loot pools. Model listed is QL 200 interpolation. Classic agent rifle with good crits and regular damage.",
      stats: {
        ql: { value: "1-200", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "2.9s", quality: "" },
        rSpeed: { value: "1.1s", quality: "g" },
        range: { value: "28 m", quality: "" },
        minDamage: { value: "10", quality: "" },
        maxDamage: { value: "410", quality: "g" },
        critMod: { value: "280", quality: "g" },
        attackCap: { value: "1330", quality: "g" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Aimed Shot", quality: "" },
        reqs: {
          Profession: { value: "Agent", quality: "" },
          Rifle: { value: "941", quality: "" },
          "Aimed shot": { value: "471", quality: "" },
        },
        mods: {
          Concealment: { value: "10", quality: "" },
          "NCU memory": { value: "8", quality: "" },
        },
      },
      auno: "https://auno.org/ao/db.php?id=160192",
      profs: ["Agent"],
      diff: 2,
    },
    "Shadowfade Rifle": {
      name: "Shadowfade Rifle",
      min: 1,
      max: 200,
      type: "Rifle",
      blurb:
        "Demo weapon listing for PRK only weapons. Examination will be reserved until seen in game. Current stats are from screenshots.",
      stats: {
        ql: { value: "1", quality: "" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "1.5s", quality: "" },
        rSpeed: { value: "1.5s", quality: "" },
        range: { value: "30 m", quality: "" },
        minDamage: { value: "83", quality: "" },
        maxDamage: { value: "171", quality: "" },
        critMod: { value: "150", quality: "" },
        attackCap: { value: "700", quality: "" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fling Shot, Aimed Shot", quality: "" },
        reqs: {
          Rifle: { value: "321", quality: "" },
          "Aimed shot": { value: "176", quality: "" },
          "Fling shot": { value: "151", quality: "" },
        },
        mods: {},
      },
      auno: false,
      profs: ["Agent"],
      diff: 69,
      prk: true,
    },
  },
  Shotgun: {
    "Krutt Assault 219 Waltzing Queen Special": {
      name: "Krutt Assault 219 Waltzing Queen Special",
      min: 60,
      max: 200,
      type: "Shotgun",
      auno: "https://auno.org/ao/db.php?id=124284",
      blurb:
        "Blitzable and part of common loot pools. Model listed is QL 184 interpolation. Notorious crit shotgun.",
      stats: {
        ql: { value: "1-184", quality: "r" },
        dual: { value: "No", quality: "" },
        aSpeed: { value: "2.13s", quality: "" },
        rSpeed: { value: "2.5s", quality: "" },
        range: { value: "22 m", quality: "" },
        minDamage: { value: "29", quality: "r" },
        maxDamage: { value: "178", quality: "r" },
        critMod: { value: "1143", quality: "g" },
        attackCap: { value: "2301", quality: "g" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "", quality: "" },
        specials: { value: "Fling Shot", quality: "" },
        reqs: {
          Shotgun: { value: "794", quality: "" },
          "Fling shot": { value: "398", quality: "" },
        },
        mods: {
          Stamina: { value: "24", quality: "" },
          Intelligence: { value: "24", quality: "" },
          "Computer literacy": { value: "20", quality: "" },
        },
      },
      profs: ["Trader"],
      diff: 2,
    },
  },
  Smg: {
    "Gamma Ejector": {
      name: "Gamma Ejector",
      min: 41,
      max: 100,
      type: "Smg",
      blurb:
        "Drops from bodyguards in Foremans. A decent smg in a drought. Virtually right hand only because of the multi check.",
      stats: {
        ql: { value: "68", quality: "" },
        dual: { value: "Yes", quality: "" },
        aSpeed: { value: "1s", quality: "g" },
        rSpeed: { value: "3s", quality: "r" },
        range: { value: "20 m", quality: "" },
        minDamage: { value: "14", quality: "" },
        maxDamage: { value: "215", quality: "g" },
        critMod: { value: "78", quality: "" },
        attackCap: { value: "", quality: "" },
        init: { value: "Ranged", quality: "" },
        multi: { value: "495", quality: "r" },
        specials: { value: "Burst", quality: "" },
        reqs: {
          Smg: { value: "278", quality: "" },
          Burst: { value: "210", quality: "" },
          Level: { value: "41", quality: "r" },
        },
        mods: {},
      },
      auno: "https://auno.org/ao/db.php?id=156770",
      profs: ["Fixer", "Soldier"],
      diff: 4,
    },
  },
};

export default db;
